---
name: 'nix build'

on:
  pull_request:
  push:
    branches:
      - master
    tags:
      - '*'

concurrency:
  group: nix-build-${{ github.event.pull_request.number || github.sha }}-${{ github.repository }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  nix-build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone
        uses: actions/checkout@v7
        with:
          submodules: true

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Build with Nix
        run: nix build . --no-link
